-- ModaBase MySQL Tablo Yapıları
-- Sadece tablo oluşturma komutları (veri yok)

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- User tablosu
CREATE TABLE IF NOT EXISTS User (
  id VARCHAR(255) PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  passwordHash TEXT,
  name VARCHAR(255),
  surname VARCHAR(255),
  phone VARCHAR(50),
  role VARCHAR(50) DEFAULT 'USER',
  isActive BOOLEAN DEFAULT TRUE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Category tablosu
CREATE TABLE IF NOT EXISTS Category (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  slug VARCHAR(255) UNIQUE NOT NULL,
  description TEXT,
  image TEXT,
  defaultTaxRate FLOAT DEFAULT 10.0,
  isActive BOOLEAN DEFAULT TRUE,
  parentId VARCHAR(255),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Product tablosu
CREATE TABLE IF NOT EXISTS Product (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE NOT NULL,
  description TEXT NOT NULL,
  price FLOAT NOT NULL,
  originalPrice FLOAT,
  images TEXT NOT NULL,
  stock INT DEFAULT 0,
  categoryId VARCHAR(255) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_category (categoryId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Order tablosu
CREATE TABLE IF NOT EXISTS `Order` (
  id VARCHAR(255) PRIMARY KEY,
  userId VARCHAR(255),
  status VARCHAR(50) DEFAULT 'PENDING',
  total FLOAT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_user (userId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- OrderItem tablosu
CREATE TABLE IF NOT EXISTS OrderItem (
  id VARCHAR(255) PRIMARY KEY,
  orderId VARCHAR(255) NOT NULL,
  productId VARCHAR(255) NOT NULL,
  quantity INT NOT NULL,
  price FLOAT NOT NULL,
  INDEX idx_order (orderId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Address tablosu
CREATE TABLE IF NOT EXISTS Address (
  id VARCHAR(255) PRIMARY KEY,
  userId VARCHAR(255) NOT NULL,
  title VARCHAR(255),
  name VARCHAR(255),
  surname VARCHAR(255),
  email VARCHAR(255),
  phone VARCHAR(50),
  city VARCHAR(100),
  district VARCHAR(100),
  neighborhood VARCHAR(100),
  address TEXT,
  isDefault BOOLEAN DEFAULT FALSE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_user (userId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- BlogPost tablosu
CREATE TABLE IF NOT EXISTS BlogPost (
  id VARCHAR(255) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE NOT NULL,
  excerpt TEXT NOT NULL,
  content LONGTEXT NOT NULL,
  author VARCHAR(255) NOT NULL,
  publishedAt DATETIME,
  tags JSON,
  image TEXT NOT NULL,
  readTime INT NOT NULL,
  category VARCHAR(100) NOT NULL,
  viewCount INT DEFAULT 0,
  isPublished BOOLEAN DEFAULT FALSE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Business tablosu
CREATE TABLE IF NOT EXISTS Business (
  id VARCHAR(255) PRIMARY KEY,
  businessName VARCHAR(255) NOT NULL,
  businessType VARCHAR(100),
  taxNumber VARCHAR(20) UNIQUE,
  email VARCHAR(255) UNIQUE,
  phone VARCHAR(50),
  address TEXT,
  city VARCHAR(100),
  contactName VARCHAR(255),
  contactSurname VARCHAR(255),
  contactEmail VARCHAR(255),
  password TEXT,
  isActive BOOLEAN DEFAULT FALSE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ProductVariant tablosu
CREATE TABLE IF NOT EXISTS ProductVariant (
  id VARCHAR(255) PRIMARY KEY,
  productId VARCHAR(255) NOT NULL,
  size VARCHAR(50),
  color VARCHAR(100),
  colorCode VARCHAR(10),
  stock INT DEFAULT 0,
  price FLOAT,
  isActive BOOLEAN DEFAULT TRUE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_product (productId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Cart tablosu
CREATE TABLE IF NOT EXISTS Cart (
  id VARCHAR(255) PRIMARY KEY,
  userId VARCHAR(255),
  isArchived BOOLEAN DEFAULT FALSE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- CartItem tablosu
CREATE TABLE IF NOT EXISTS CartItem (
  id VARCHAR(255) PRIMARY KEY,
  cartId VARCHAR(255) NOT NULL,
  productId VARCHAR(255) NOT NULL,
  quantity INT DEFAULT 1,
  size VARCHAR(50),
  color VARCHAR(100),
  INDEX idx_cart (cartId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Review tablosu
CREATE TABLE IF NOT EXISTS Review (
  id VARCHAR(255) PRIMARY KEY,
  userId VARCHAR(255) NOT NULL,
  productId VARCHAR(255) NOT NULL,
  rating INT NOT NULL,
  title VARCHAR(255),
  comment TEXT,
  isApproved BOOLEAN DEFAULT FALSE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_product (productId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- SEOSettings tablosu
CREATE TABLE IF NOT EXISTS SEOSettings (
  id VARCHAR(255) PRIMARY KEY,
  pageType VARCHAR(50),
  pageId VARCHAR(255),
  productId VARCHAR(255) UNIQUE,
  categoryId VARCHAR(255) UNIQUE,
  pageSlug VARCHAR(255),
  metaTitle VARCHAR(255),
  metaDescription TEXT,
  keywords TEXT,
  isActive BOOLEAN DEFAULT TRUE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ShippingCompany tablosu
CREATE TABLE IF NOT EXISTS ShippingCompany (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  code VARCHAR(100) UNIQUE NOT NULL,
  apiUrl TEXT,
  apiKey TEXT,
  isActive BOOLEAN DEFAULT TRUE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TransferNotification tablosu
CREATE TABLE IF NOT EXISTS TransferNotification (
  id VARCHAR(255) PRIMARY KEY,
  orderId VARCHAR(255) NOT NULL,
  customerName VARCHAR(255),
  customerEmail VARCHAR(255),
  customerPhone VARCHAR(50),
  transferAmount FLOAT,
  transferDate DATETIME,
  transferNote TEXT,
  status VARCHAR(50) DEFAULT 'PENDING',
  businessId VARCHAR(255),
  iban VARCHAR(50),
  accountHolder VARCHAR(255),
  bankName VARCHAR(255),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_order (orderId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;

-- Tablolar başarıyla oluşturuldu!
-- Sonraki adım: Verileri yükleyin
